main: walker\Main
api: [1.10.0, 1.12.0, 2.0.0]
load: POSTWORLD

name: Walker
description: A box full of fun toys and tools
version: 1.2.1
author: aliuly

permissions:
  toybox.magiccarpet:
    default: op
    description: "MagicCarpet command"
